"""volume, image table

Revision ID: 81d1be2ad1f5
Revises: 59ab4dee883f
Create Date: 2022-03-21 01:20:06.889209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d1be2ad1f5'
down_revision = '59ab4dee883f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdrom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cdrom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cdrom_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cdrom_url'), ['url'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('volume',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_size'), ['size'], unique=False)

    op.create_table('image',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('volume_uuid', sa.String(length=36), nullable=True),
    sa.Column('cdrom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cdrom_id'], ['cdrom.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volume_uuid'], ['volume.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_name'), ['name'], unique=True)

    op.create_table('domain',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('volume_uuid', sa.String(length=36), nullable=True),
    sa.Column('cdrom_id', sa.Integer(), nullable=True),
    sa.Column('image_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cdrom_id'], ['cdrom.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_uuid'], ['image.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volume_uuid'], ['volume.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index('ix_domains_name')

    op.drop_table('domains')
    with op.batch_alter_table('cdroms', schema=None) as batch_op:
        batch_op.drop_index('ix_cdroms_url')

    op.drop_table('cdroms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdroms',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('cdroms', schema=None) as batch_op:
        batch_op.create_index('ix_cdroms_url', ['url'], unique=False)

    op.create_table('domains',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index('ix_domains_name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_name'))

    op.drop_table('domain')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_name'))

    op.drop_table('image')
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_size'))

    op.drop_table('volume')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('cdrom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cdrom_url'))
        batch_op.drop_index(batch_op.f('ix_cdrom_name'))

    op.drop_table('cdrom')
    # ### end Alembic commands ###
